### ISSUE TITLE
Generic types incompatibility in DAG Renderer

### ISSUE THREAD

**Issue by stefanches7** [nextflow-io/nf-prov#26] opened 2024-03-19 15:08 UTC
![image](https://github.com/nextflow-io/nf-prov/assets/17748742/2eba3cdd-ae3d-4235-bee2-1cf5d3a0fe53)

**Comment by bentsherman** [comment] 2024-03-22 15:42
Think you are working with the ro-crate branch which is not stable. Unable to reproduce on master, closing

**Closed as completed by bentsherman** 2024-03-22 15:42 UTC
